### ISSUE TITLE
Wood

### ISSUE THREAD

**Issue by whichonespink44** [whichonespink44/Appalachia#13]
## Overview

Appalachia will contain a variety of wood sets, consisting (initially) of the following blocks:

`logs, planks, slabs, stairs, fences, fence gates, and leaves`

Eventually, sets will also include the more 'advanced' blocks, like `doors, buttons, pressure plates`, etc, but we should concentrate on the basics first, and save the more complicated blocks for later.

There's currently a (crude) system in place for quickly adding new wood sets, but it's still a tedious affair. This is something we'll be looking to improve as the mod evolves.

## Logs

The most important block is the log block since it will be used in Appalachia's trees... all the other blocks will be based on the log block.

### Variants

Each log block will also have a few different variants. Variants only apply to the log blocks. The other blocks in the wood set will not get created for these variants since they would look exactly the same as their original counterparts.

#### Mossy

Ideally, it would be great if we could come up with a system for 'dynamically' adding a mossy overlay to the original log block, but for now let's just make a totally separate mossy block with its own unique texture.

### Bark types

In real-life, a tree's bark will go through various forms as it ages... it would be great to bring that aspect into Appalachia. For example, if we do a Paper Birch log, it should have a few different types of bark. To keep it simple, let's use the following convention, which represents 3 different bark stages:
```
Paper Birch Log
Paper Birch Log (Young)
Paper Birch Log (Mature)
```
(Each of those would be its own block, and each would have a mossy version)

### Log Checklist

This website will be our log bible: http://treebarkid.com/

- [x] American Beech
- [x] American Chestnut
- [x] American Elm
- [x] Ash
- [x] Bitternut Hickory
- [x] Black Cherry
- [x] Blackgum
- [x] Black Locust
- [x] Black Oak
- [x] Blue Beech
- [x] Black Walnut
- [x] Box Elder
- [x] Buckeye
- [x] Cedar
- [x] Dogwood
- [x] Tulip Poplar
- [x] Hackberry
- [x] Hop Hornbeam
- [x] Honey Locust
- [x] Persimmon
- [x] Pignut Hickory
- [x] Red Elm
- [x] Red Maple
- [x] Red Oak group
- [x] River Birch
- [x] Sassafras
- [x] Shortleaf Pine
- [x] Sugar Maple
- [x] Sycamore
- [x] Shagbark Hickory
- [x] White Oak group
- [x] White Pine
- [x] White Walnut
- [x] Yellow Birch

- [ ] Moss

**Comment by garantiertnicht** [comment]
Couln't we use Blockstates for mossy and age?

**Comment by whichonespink44** [comment]
Might be a good idea... that would allow us to have different textures for the same block... only potential issue I can think of is, how would the user place the various states?

**Comment by garantiertnicht** [comment]
`damageDropped()` and the opposite Method - Look at the Vanilla Wool I guess, can't right now.

**Comment by MoeBoy76** [comment]
If they all extend an `AppalachianLog` with an `EnumProperty` containing those values then it will be quite simple

**Comment by garantiertnicht** [comment]
I thought of it a bit longer. Blocks have 4 bit of data. We could do x/y as 1st bit, mossy 2nd, and the remaining two for age. But we would not be able to have all closed variants (would require a 5th bit wich we don't have), wich is might not what is wanted.

**Comment by whichonespink44** [comment]
Closing this... we can maybe do mossy versions later on.
