### ISSUE TITLE
No sapling growth

### ISSUE THREAD

**Issue by lightningo7** [whichonespink44/Appalachia#186]
After picking up a sapling off the ground I decided to plant it and see what it would look like, after waiting around roughly 5 minutes I got impatient of watiing and started bonemealing the sapling, after another 5 minutes of that not working I figured there's something wrong.

Steps to reproduce:
1. Plant sapling in APL biome
2. Wait or Bonemeal sapling
3. Watch the failure of it

**Comment by whichonespink44** [comment]
Fixed in d2e88ca
