### ISSUE TITLE
Default world type

### ISSUE THREAD

**Issue by lightningo7** [whichonespink44/Appalachia#19]
This biome is currently generating with no decorations viewable here http://prntscr.com/d8l9g7

**Comment by whichonespink44** [comment]
Hmm, looks like you loaded it without RTG installed... didnt think that was possible. It's supposed to warn you if you don't have the minimum RTG version installed.

**Comment by lightningo7** [comment]
It's definitely installed, though I forgot to set the world type, I think we should disable the other world types when using appalachia

**Comment by whichonespink44** [comment]
That's probably a little too intrusive (I can hear the complaints already) - but yeah, it would be good to do _something_ ... maybe disabling the other word types isn't a bad idea actually.... are there any alternatives?

**Comment by lightningo7** [comment]
Another alternative might be not allowing the Appalachia biomes to generate if the Realistic world generation setting is selected

**Comment by whichonespink44** [comment]
That's probably a better way to go... we'll probably need to remove them from the registry somehow, probably using a Forge event. I think there's a BiomeRegistry.unregister() method somewhere.

**Comment by MoeBoy76** [comment]
Perhaps also add an option similar to BoP where we set the world type to Realistic by default?

**Comment by whichonespink44** [comment]
RTG already does what BOP does, which is display a 'world type notification' screen... i dont think BOP actually sets the world type, just tells the user which world type they need to use.

**Comment by whichonespink44** [comment]
If we can default to Realistic though, that would be sweet.

**Comment by MoeBoy76** [comment]
BoP does, the config option is on by default i think, cos it shows up every time i got to test stuff in SP

**Comment by srs-bsns** [comment]
> i dont think BOP actually sets the world type

BoP has a config option that will automatically set the WorldType to BIOMESOP.
https://github.com/Glitchfiend/BiomesOPlenty/blob/BOP-1.11.x-6.0.x/src/main/java/biomesoplenty/common/config/MiscConfigurationHandler.java#L53

Edit:
![skowpoke](https://cloud.githubusercontent.com/assets/8453133/20407161/2292bf40-acde-11e6-81c4-06b26a01336e.gif)

**Comment by whichonespink44** [comment]
Sweeeeeet! We should definitely do that as well... should probably do the config option too.

**Comment by whichonespink44** [comment]
So I tried doing this earlier today, but it looks like it's only possible in 1.11 because the 'selectedIndex' field in CreateWorldGui is private, which is the field that we need to change in order to set the default world type.

I was thinking about doing some voodoo to hack in there and set it to RTG's world type ID, but not sure it's worth it.

**Comment by whichonespink44** [comment]
Added to RTG in Team-RTG/Realistic-Terrain-Generation@ff96ab1
