### ISSUE TITLE
Floating snow above fallen leaves

### ISSUE THREAD

**Issue by whichonespink44** [whichonespink44/Appalachia#4]
![2016-10-16_23 27 42](https://cloud.githubusercontent.com/assets/10927161/19421443/315ada88-93f9-11e6-8cf6-be821da82e7e.png)

**Comment by whichonespink44** [comment]
This required a change to RTG core: [9c17cf2](https://github.com/Team-RTG/Realistic-Terrain-Generation/commit/9c17cf2d25fe5529886c45fabfd5d6f4c0a051e6)

**Comment by MoeBoy76** [comment]
additionally we could have a 'snowy' variation of the leaves?

**Comment by whichonespink44** [comment]
yeah, that might look cool... maybe speckled white on top so some of the colour shows through? we could probably use the same logic that RTG uses when placing snow layers too so everything syncs up.
