### ISSUE TITLE
American Beech (EUR 4, NA 13)

### ISSUE THREAD

**Issue by whichonespink44** [whichonespink44/Appalachia#45]
EUR 4:
![eur 4](https://cloud.githubusercontent.com/assets/10927161/20578705/7ed235ce-b1c0-11e6-9f70-dc03f938f1c7.png)
[EUR 4.zip](https://github.com/Team-RTG/Appalachia/files/610009/EUR.4.zip)

NA 13:
![na 13](https://cloud.githubusercontent.com/assets/10927161/20578742/c20a0902-b1c0-11e6-8ef6-fb4f7fba9268.png)
[NA 13.zip](https://github.com/Team-RTG/Appalachia/files/610015/NA.13.zip)

**Comment by ghost** [comment]
EUR 4

**Comment by ghost** [comment]
NA 13
