### ISSUE TITLE
Ash (EUR 2, NA 12)

### ISSUE THREAD

**Issue by whichonespink44** [whichonespink44/Appalachia#48]
EUR 2:
![eur 2](https://cloud.githubusercontent.com/assets/10927161/20579412/53637e44-b1c4-11e6-8802-610f68fe08ab.png)
[EUR 2.zip](https://github.com/Team-RTG/Appalachia/files/610051/EUR.2.zip)

NA 12:
![na 12](https://cloud.githubusercontent.com/assets/10927161/20579463/906144ac-b1c4-11e6-9321-e472fdc6ef16.png)
[NA 12.zip](https://github.com/Team-RTG/Appalachia/files/610058/NA.12.zip)

**Comment by ghost** [comment]
EUR 2 (actually an ash)

**Comment by ghost** [comment]
NA 12 (actually an ash)
