### ISSUE TITLE
Blue Beech (AFR 10, AFR 12, EU 9)

### ISSUE THREAD

**Issue by whichonespink44** [whichonespink44/Appalachia#54]
AFR 10:
![afr 10](https://cloud.githubusercontent.com/assets/10927161/20578009/ffd2baa8-b1bc-11e6-86e6-14f9430df3f9.png)
[AFR 10.zip](https://github.com/Team-RTG/Appalachia/files/609963/AFR.10.zip)

AFR 12:
![afr 12](https://cloud.githubusercontent.com/assets/10927161/20578036/253e4b86-b1bd-11e6-9b27-9bdcc1705bf7.png)
[AFR 12.zip](https://github.com/Team-RTG/Appalachia/files/609964/AFR.12.zip)

EU 9:
![eu 9](https://cloud.githubusercontent.com/assets/10927161/20578168/e49b7da0-b1bd-11e6-9b69-3a89da494121.png)
[EU 9.zip](https://github.com/Team-RTG/Appalachia/files/609968/EU.9.zip)

**Comment by ghost** [comment]
AFR 10 looks decent

**Comment by ghost** [comment]
as does AFR 12

**Comment by ghost** [comment]
EUR 9 too
