### ISSUE TITLE
Persimmon (SA 12, SA 21)

### ISSUE THREAD

**Issue by whichonespink44** [whichonespink44/Appalachia#64]
SA 12:
![sa 12](https://cloud.githubusercontent.com/assets/10927161/20581951/67ff59ee-b1d4-11e6-8314-9b54091cc109.png)
[SA 12.zip](https://github.com/Team-RTG/Appalachia/files/610220/SA.12.zip)

SA 21:
![sa 21](https://cloud.githubusercontent.com/assets/10927161/20581977/941a5c68-b1d4-11e6-9a7e-0d90cc77c63c.png)
[SA 21.zip](https://github.com/Team-RTG/Appalachia/files/610222/SA.21.zip)

**Comment by ghost** [comment]
SA 12

**Comment by ghost** [comment]
SA 21
