### ISSUE TITLE
Shortleaf Pine (NA 3, NA 13)

### ISSUE THREAD

**Issue by whichonespink44** [whichonespink44/Appalachia#71]
NA 3:
![na 3](https://cloud.githubusercontent.com/assets/10927161/20579062/6ca87280-b1c2-11e6-9851-535820d32fde.png)
[NA 3.zip](https://github.com/Team-RTG/Appalachia/files/610031/NA.3.zip)

NA 13:
![na 13](https://cloud.githubusercontent.com/assets/10927161/20579086/8926a06c-b1c2-11e6-9a6f-67fc5dfd58ab.png)
[NA 13.zip](https://github.com/Team-RTG/Appalachia/files/610034/NA.13.zip)

**Comment by ghost** [comment]
NA 3

**Comment by ghost** [comment]
NA 13
