### ISSUE TITLE
White Oak (NA 10*)

### ISSUE THREAD

**Issue by whichonespink44** [whichonespink44/Appalachia#75]
EUR 13:
![eur 13](https://cloud.githubusercontent.com/assets/10927161/20578949/d54c1572-b1c1-11e6-893e-4334afa5c347.png)
[EUR 13.zip](https://github.com/Team-RTG/Appalachia/files/610024/EUR.13.zip)

NA 10:
![na 10](https://cloud.githubusercontent.com/assets/10927161/20578995/09f84bd8-b1c2-11e6-8ad7-d5f4605fb6b2.png)
[NA 10.zip](https://github.com/Team-RTG/Appalachia/files/610027/NA.10.zip)

**Comment by ghost** [comment]
EUR 13

**Comment by ghost** [comment]
NA 10 (actually a white oak)
