### ISSUE TITLE
White Pine (NA 5, NA 18)

### ISSUE THREAD

**Issue by whichonespink44** [whichonespink44/Appalachia#76]
NA 5:
![na 5](https://cloud.githubusercontent.com/assets/10927161/20578231/3ab6319e-b1be-11e6-98a7-13b96a70df94.png)
[NA 5.zip](https://github.com/Team-RTG/Appalachia/files/609972/NA.5.zip)

NA 18:
![na 18](https://cloud.githubusercontent.com/assets/10927161/20578267/727d8276-b1be-11e6-8282-7804899c8c4d.png)
[NA 18.zip](https://github.com/Team-RTG/Appalachia/files/609976/NA.18.zip)

**Comment by ghost** [comment]
NA 5 or NA 18
