### ISSUE TITLE
White Walnut (EUR 13, EUR 2)

### ISSUE THREAD

**Issue by whichonespink44** [whichonespink44/Appalachia#77]
EUR 13:
![eur 13](https://cloud.githubusercontent.com/assets/10927161/20582022/f12e9310-b1d4-11e6-858d-1005230e006d.png)
[EUR 13.zip](https://github.com/Team-RTG/Appalachia/files/610225/EUR.13.zip)

EUR 2:
![eur 2](https://cloud.githubusercontent.com/assets/10927161/20582025/fafd296a-b1d4-11e6-8c27-e3674852d736.png)
[EUR 2.zip](https://github.com/Team-RTG/Appalachia/files/610226/EUR.2.zip)

**Comment by ghost** [comment]
EUR 13

**Comment by ghost** [comment]
EUR 2
